apiVersion: v1
kind: Pod
metadata:
  name: debug-mem2
  namespace: rq1-model3
spec:
    restartPolicy: Never
    nodeSelector:
      experiment-model: model3
    tolerations:
      - operator: Exists
    containers:
      - name: debug
        image: pippina2/rq1-probe:v2
        command: ["/bin/sh"]
        args:
          - "-c"
          - "for c in 0 1 2 3; do echo CPU $c:; taskset -c $c /usr/local/bin/matmul --kind ptrchase --buf-kb 65536 --M 48 --K 1 --period-us 0 --n-jobs 1 --warmup 0 --priority  0 --cpu $c --logfile /tmp/test$c.csv; echo EXIT:$?; done; sleep 300"
        securityContext:
          capabilities:
            add: ["SYS_NICE", "IPC_LOCK"]
