#!/usr/bin/env python3
"""Writes the validation manifests from budgets.csv (standard library only).

    python3 validation/make_manifests.py

One manifest per scenario x route x tolerance x interference: 2 x 2 x 3 x 2 = 24 files in manifests/<scenario>/<route>/
(<p>_none.yaml and <p>_memory.yaml). The interference is NOT in a manifest: run_validation.sh starts the memory enemy
around the runs whose file name ends in _memory.yaml. Each manifest is self-contained: the RtClaimParameters with
runtime = Q* (us), the ResourceClaimTemplate and the Pod (multi-core also a ConfigMap with the config of the run).

To change the budgets, edit budgets.csv (or re-export it from the notebook) and run this again.
"""
import csv, json, math, pathlib, re

HERE = pathlib.Path(__file__).resolve().parent
RQ2 = HERE.parent
JOBS = 50000
IMAGE = "pippina2/rq2-workload:v2"
PERIOD_US = 41667
# each scenario is validated on a VM that did NOT profile it (S1: single-core on worker6, multi-core on worker7)
SCEN = {
    "multi_core": dict(short="multi", node="rt-k8s-worker-6", count=2, cpus=[1, 2], hostpath="/var/lib/rq2/results/multi_core"),
    "single_core": dict(short="single", node="rt-k8s-worker-7", count=1, cpus=[1], hostpath="/var/lib/rq2/results/single_core"),
}
ROUTES = {"route1": ("r1", "Route 1: Q = C_p^stress(S1) x alpha_drift"),
          "route2b": ("r2b", "Route 2b: Q = C_p^base(S1) x alpha_cores,platform(m) x alpha_drift")}
TOL = {"0.1": "p1e-1", "0.01": "p1e-2", "0.001": "p1e-3"}
COND = {"none": ("none", "without interference"), "memory": ("mem", "with the memory enemy (started by run_validation.sh)")}

multi_cfg = json.load(open(RQ2 / "workload" / "configs" / "multi_core.json"))
# the single-core args are read from the repo's pod spec, so both stay consistent with the profiling runs
single_args = re.findall(r'^\s+- "(--[^"]+)"', (RQ2 / "workload" / "pods" / "single_core_pod.yaml").read_text(), re.M)
assert any(a.startswith("--jobs=") for a in single_args) and any(a.startswith("--output=") for a in single_args)


def multi_config(run_id):
    cfg = json.loads(json.dumps(multi_cfg))
    for inst in cfg["instances"]:
        inst["jobs"] = JOBS
        inst["output"] = f"/results/{run_id}_{inst['instance_id']}.csv"
    return json.dumps(cfg, indent=2)


def single_arg_lines(run_id):
    out = []
    for a in single_args:
        if a.startswith("--jobs="):
            a = f"--jobs={JOBS}"
        elif a.startswith("--output="):
            a = f"--output=/results/{run_id}_instance0.csv"
        out.append(f'        - "{a}"')
    return "\n".join(out)


def manifest(scen, route, ptag, cond, row):
    s = SCEN[scen]
    rshort, rdesc = ROUTES[route]
    cshort, cdesc = COND[cond]
    run_id = f"rq2-val-{s['short']}-{rshort}-{ptag}-{cshort}"
    q_ms, runtime_us = float(row["Q_ms"]), int(row["runtime_us"])
    inst_desc = "instance0 on cpu1, instance1 on cpu2" if scen == "multi_core" else "instance0 on cpu1"
    head = f"""# id: {run_id}
# Online validation, {scen.replace('_', '-')}, {rdesc}
# tolerance p = {row['p']}, {cdesc}
# Budget Q* = {q_ms:.4f} ms -> reservation runtime {runtime_us} us of period {PERIOD_US} us (Q/T = {runtime_us / PERIOD_US:.3f}), from budgets.csv
# {JOBS} jobs per instance; {inst_desc}; pinned to {s['node']}.
# Generated by make_manifests.py - edit budgets.csv and regenerate instead of editing this file.
---
"""
    params = f"""apiVersion: rt.resource.example.com/v1alpha1
kind: RtClaimParameters
metadata: {{ namespace: rq2, name: "{run_id}-params" }}
spec: {{ count: {s['count']}, runtime: {runtime_us}, period: {PERIOD_US}, requestedCpus: {s['cpus']} }}
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata: {{ namespace: rq2, name: "{run_id}-claim" }}
spec:
  spec:
    resourceClassName: rt.example.com
    parametersRef: {{ apiGroup: rt.resource.example.com, kind: RtClaimParameters, name: "{run_id}-params" }}
---
"""
    pod_head = f"""apiVersion: v1
kind: Pod
metadata:
  namespace: rq2
  name: "{run_id}"
  labels: {{ app: rq2-workload, role: worker, validation: "true", interference: "{cond}" }}
spec:
  restartPolicy: Never
  nodeSelector: {{ experiment-model: rq2, kubernetes.io/hostname: {s['node']} }}
  tolerations: [{{ operator: Exists }}]
  containers:
    - name: rt-video
      image: {IMAGE}
      imagePullPolicy: IfNotPresent
"""
    claim_tail = f"""  resourceClaims:
    - {{ name: rtcpu, source: {{ resourceClaimTemplateName: "{run_id}-claim" }} }}
  volumes:
    - name: results
      hostPath: {{ path: {s['hostpath']}, type: DirectoryOrCreate }}
"""
    if scen == "multi_core":
        cfg = "\n".join("    " + line for line in multi_config(run_id).splitlines())
        cm = f"""apiVersion: v1
kind: ConfigMap
metadata: {{ namespace: rq2, name: "{run_id}-config" }}
data:
  multi_core.json: |
{cfg}
---
"""
        pod = pod_head + """      command: ["python3", "launch.py"]
      args: ["/cfg/multi_core.json"]
      securityContext: { capabilities: { add: ["SYS_NICE", "IPC_LOCK"] } }
      resources: { claims: [{ name: rtcpu }] }
      volumeMounts: [{ name: results, mountPath: /results }, { name: cfg, mountPath: /cfg }]
""" + claim_tail + f"""    - name: cfg
      configMap: {{ name: "{run_id}-config" }}
"""
        return head + cm + params + pod
    pod = pod_head + f"""      command: ["python3", "rt_video.py"]
      args:
{single_arg_lines(run_id)}
      securityContext: {{ capabilities: {{ add: ["SYS_NICE", "IPC_LOCK"] }} }}
      resources: {{ claims: [{{ name: rtcpu }}] }}
      volumeMounts: [{{ name: results, mountPath: /results }}]
""" + claim_tail
    return head + params + pod


def main():
    rows = {(r["scenario"], r["route"], r["p"]): r for r in csv.DictReader(open(HERE / "budgets.csv"))}
    n = 0
    for scen in SCEN:
        for route in ROUTES:
            out = HERE / "manifests" / scen / route
            out.mkdir(parents=True, exist_ok=True)
            for p, ptag in TOL.items():
                row = rows[(scen, route, p)]
                assert math.ceil(float(row["Q_ms"]) * 1000) == int(row["runtime_us"]), f"runtime_us is not ceil(Q_ms*1000): {scen} {route} {p}"
                for cond in COND:
                    (out / f"{ptag}_{cond}.yaml").write_text(manifest(scen, route, ptag, cond, row))
                    n += 1
    print(f"wrote {n} manifests under {HERE / 'manifests'}")


if __name__ == "__main__":
    main()
