#!/usr/bin/env python3
"""Writes the online-validation pods of the audio workload from budgets.csv (standard library only).

    python3 make_manifests.py

One self-contained file per scenario x route x tolerance x interference in pods/<scenario>/<route>/<p>_<none|memory>.yaml:
the RtClaimParameters with runtime = the budget (us) of period 10000 us, the ResourceClaimTemplate and the Pod. The HWM route has
no tolerance: one budget, pods/<scenario>/hwm/all_none.yaml and all_memory.yaml. 28 files, plus runs.csv (what each run is, where it
runs, where its files appear on the node and where to save them for step 5) and step5_input/budgets.csv (the budgets in step 4's format). The interference is NOT in a pod: the memory enemy is
started on the node around the runs whose file name ends in _memory.yaml (see README.md).

To change a budget, edit budgets.csv and run this again."""
import csv, pathlib

HERE = pathlib.Path(__file__).resolve().parent
JOBS = 50000                                   # jobs per instance: 8.3 minutes at the 10 ms period, ~50 expected exceedances at p = 1e-3
IMAGE = "pippina2/rq2-audio:v2"
NODE_DIR = "/var/lib/rq2/results/audio_validation"        # hostPath on the node; the pod writes <run id>_instance<N>.csv there
# each scenario is validated on the node that did NOT profile it (profiling: single-core on worker6, multi-core on worker7)
SCEN = {
    "multi_core": dict(short="multi", node="rt-k8s-worker-6", cpus=[1, 2], enemy_cpus="3,0"),
    "single_core": dict(short="single", node="rt-k8s-worker-7", cpus=[1], enemy_cpus="2,3,0"),
}
ROUTES = {"route1": ("r1", "Route 1: Q = C_p of the stress runs x alpha_drift"),
          "route2b": ("r2b", "Route 2b: Q = C_p of the baselines x alpha_platform(m) x alpha_drift"),
          "hwm": ("hwm", "HWM: Q = largest C of the stress runs x alpha_drift / 0.96 (one budget for every tolerance)")}
TOL = {"0.1": "p1e-1", "0.01": "p1e-2", "0.001": "p1e-3"}
M = {"single_core": 3, "multi_core": 2}          # enemy cores of the profiling (the label of Route 2b)
COND = {"none": ("none", "without interference"), "memory": ("mem", "with the memory enemy (started on the node around the run)")}


def pod_file(scen, route, ptag, cond, row):
    s = SCEN[scen]
    rshort, rdesc = ROUTES[route]
    cshort, cdesc = COND[cond]
    run_id = f"rq2-val-aud-{s['short']}-{rshort}-{ptag}-{cshort}"
    runtime, period = int(row["runtime_us"]), int(row["period_us"])
    cpus = ",".join(map(str, s["cpus"]))
    text = f"""# id: {run_id}
# Online validation of the audio workload, {scen.replace('_', '-')}, {rdesc}
# {'no tolerance (one budget for every p)' if row['p'] == 'all' else 'tolerance p = ' + row['p']}, {cdesc}
# Reservation: runtime {runtime} us of period {period} us (Q/T = {runtime / period:.3f}), from budgets.csv. {JOBS} jobs per instance; cpus {cpus}; pinned to {s['node']}.
# Generated by make_manifests.py: edit budgets.csv and regenerate instead of editing this file.
---
apiVersion: rt.resource.example.com/v1alpha1
kind: RtClaimParameters
metadata: {{ namespace: rq2, name: "{run_id}-params" }}
spec: {{ count: {len(s['cpus'])}, runtime: {runtime}, period: {period}, requestedCpus: {s['cpus']} }}
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata: {{ namespace: rq2, name: "{run_id}-claim" }}
spec:
  spec:
    resourceClassName: rt.example.com
    parametersRef: {{ apiGroup: rt.resource.example.com, kind: RtClaimParameters, name: "{run_id}-params" }}
---
apiVersion: v1
kind: Pod
metadata:
  namespace: rq2
  name: "{run_id}"
  labels: {{ app: rq2-workload, role: worker, validation: "true", interference: "{cond}" }}
spec:
  restartPolicy: Never
  nodeSelector: {{ experiment-model: rq2, kubernetes.io/hostname: {s['node']} }}
  tolerations: [{{ operator: Exists }}]
  containers:
    - name: audio
      image: {IMAGE}
      imagePullPolicy: IfNotPresent
      command: ["python3", "run.py"]
      args: ["cpus=[{cpus}]", "period_ms={period / 1000:g}", "jobs={JOBS}", "output=/results/{run_id}"]
      securityContext: {{ capabilities: {{ add: ["SYS_NICE", "IPC_LOCK"] }} }}
      resources: {{ claims: [{{ name: rtcpu }}] }}
      volumeMounts: [{{ name: results, mountPath: /results }}]
  resourceClaims:
    - {{ name: rtcpu, source: {{ resourceClaimTemplateName: "{run_id}-claim" }} }}
  volumes:
    - name: results
      hostPath: {{ path: {NODE_DIR}, type: DirectoryOrCreate }}
"""
    return run_id, text


def main():
    rows = {(r["scenario"], r["route"], r["p"]): r for r in csv.DictReader(open(HERE / "budgets.csv"))}
    runs = []
    for scen, s in SCEN.items():
        for route in ROUTES:
            out = HERE / "pods" / scen / route
            out.mkdir(parents=True, exist_ok=True)
            for p, ptag in (TOL.items() if route != "hwm" else [("all", "all")]):
                row = rows[(scen, route, p)]
                for cond in COND:
                    run_id, text = pod_file(scen, route, ptag, cond, row)
                    path = out / f"{ptag}_{cond}.yaml"
                    path.write_text(text)
                    runs.append(dict(run_id=run_id, scenario=scen, route=route, p=p, interference=cond, node=s["node"], enemy_cpus=s["enemy_cpus"] if cond == "memory" else "",
                                     runtime_us=row["runtime_us"], period_us=row["period_us"], jobs=JOBS, pod_file=str(path.relative_to(HERE)),
                                     node_files=f"{NODE_DIR}/{run_id}_instance*.csv", save_results_in=f"results/{scen}/{route}/{ptag}_{cond}"))
    # the same budgets in the format of step 4's budgets.csv, so that step 5's validate.py can check the online runs against exactly these
    # budgets:  python3 validate.py check --step4 <this folder>/step5_input --results <this folder>/results
    label = {"route1": lambda s: "Route 1", "route2b": lambda s: f"Route 2b (m={M[s]})", "hwm": lambda s: "HWM"}
    out5 = HERE / "step5_input"
    out5.mkdir(exist_ok=True)
    with open(out5 / "budgets.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["scenario", "route", "p", "Q_ms", "Q_over_T", "runtime_us", "period_us", "admitted"])
        for (scen, route, p), r in rows.items():
            for pp in ([0.001, 0.01, 0.1] if p == "all" else [float(p)]):
                q, T = int(r["runtime_us"]), int(r["period_us"])
                w.writerow([scen, label[route](scen), pp, q / 1000, q / T, q, T, q / T <= 0.95])
    with open(HERE / "runs.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(runs[0]))
        w.writeheader()
        w.writerows(runs)
    print(f"wrote {len(runs)} pods under {HERE / 'pods'} and runs.csv")


if __name__ == "__main__":
    main()
