apiVersion: v1
kind: Pod
metadata:
  name: sriov-probe-client
  labels:
    app: sriov-probe-client
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  nodeSelector:
    sriov-probe-role: client
  tolerations:
    - operator: Exists
  containers:
    - name: probe-client
      image: networkstatic/iperf3
      command: ["sleep", "infinity"]
  restartPolicy: Never
