apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: rt-capi
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    kind: KubeadmControlPlane
    name: rt-capi-control-plane
  infrastructureRef:
    kind: AzureCluster
    name: rt-capi
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: rt-capi
  namespace: default
spec:
  identityRef:
    kind: AzureClusterIdentity
    name: cluster-identity
  location: swedencentral
  networkSpec:
    subnets:
      - name: control-plane-subnet
        role: control-plane
      - name: node-subnet
        role: node
    vnet:
      name: rt-capi-vnet
  resourceGroup: rt-capi
  subscriptionID: d06f8f89-f7d3-46b3-b7a8-649244fb54c6
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: rt-capi-control-plane
  namespace: default
spec:
  version: v1.28.15
  kubeadmConfigSpec:
    preKubeadmCommands:
      - apt-get update
      - apt-get install -y git make gcc pkg-config curl jq
      - git clone -b rt https://github.com/nasim-samimi/containerd.git /tmp/containerd-rt
      - cd /tmp/containerd-rt && make
      - cd /tmp/containerd-rt && sudo make install
      - sudo mkdir -p /etc/containerd
      - sudo containerd config default | sudo tee /etc/containerd/config.toml
      - sudo mkdir -p /opt/cni/bin
      - curl -L https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz | sudo tar -C /opt/cni/bin -xz
      - apt-get install -y libseccomp-dev
      - git clone -b rt https://github.com/nasim-samimi/runc.git /tmp/runc-rt
      - cd /tmp/runc-rt && make
      - cd /tmp/runc-rt && sudo install -D -m0755 runc /usr/local/sbin/runc
      - sudo systemctl daemon-reload
      - sudo systemctl restart containerd
    files:
      - contentFrom:
          secret:
            key: control-plane-azure.json
            name: rt-capi-control-plane-azure-json
        owner: root:root
        path: /etc/kubernetes/azure.json
        permissions: "0644"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          feature-gates: "DynamicResourceAllocation=true"
        name: '{{ ds.meta_data["local_hostname"] }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          feature-gates: "DynamicResourceAllocation=true"
        name: '{{ ds.meta_data["local_hostname"] }}'
    verbosity: 10
  machineTemplate:
    infrastructureRef:
      kind: AzureMachineTemplate
      name: rt-capi-control-plane
  replicas: 1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: rt-capi-control-plane
  namespace: default
spec:
  template:
    spec:
      vmSize: Standard_D4ds_v5
      osDisk:
        diskSizeGB: 128
        osType: Linux
      sshPublicKey: ""
      image:
        sharedGallery:
          subscriptionID: d06f8f89-f7d3-46b3-b7a8-649244fb54c6
          resourceGroup: rg-rtAKS
          gallery: rtUbuntu
          name: rtUbuntu24.04
          version: "1.0.2"
      securityProfile:
        securityType: TrustedLaunch
        uefiSettings:
          vTpmEnabled: true
          secureBootEnabled: false
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: rt-capi-md-0
  namespace: default
spec:
  clusterName: rt-capi
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: rt-capi
      nodepool: rt-capi-md-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: rt-capi
        nodepool: rt-capi-md-0
    spec:
      clusterName: rt-capi
      version: v1.28.15
      bootstrap:
        configRef:
          kind: KubeadmConfigTemplate
          name: rt-capi-md-0
      infrastructureRef:
        kind: AzureMachineTemplate
        name: rt-capi-md-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: rt-capi-md-0
  namespace: default
spec:
  template:
    spec:
      vmSize: Standard_D4ds_v5
      osDisk:
        diskSizeGB: 128
        osType: Linux
      sshPublicKey: ""
      image:
        sharedGallery:
          subscriptionID: d06f8f89-f7d3-46b3-b7a8-649244fb54c6
          resourceGroup: rg-rtAKS
          gallery: rtUbuntu
          name: rtUbuntu24.04
          version: "1.0.2"
      securityProfile:
        securityType: TrustedLaunch
        uefiSettings:
          vTpmEnabled: true
          secureBootEnabled: false
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: rt-capi-md-0
  namespace: default
spec:
  template:
    spec:
      preKubeadmCommands:
        - apt-get update
        - apt-get install -y git make gcc pkg-config curl jq
        - git clone -b rt https://github.com/nasim-samimi/containerd.git /tmp/containerd-rt
        - cd /tmp/containerd-rt && make
        - cd /tmp/containerd-rt && sudo make install
        - sudo mkdir -p /etc/containerd
        - sudo containerd config default | sudo tee /etc/containerd/config.toml
        - sudo mkdir -p /opt/cni/bin
        - curl -L https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz | sudo tar -C /opt/cni/bin -xz
        - apt-get install -y libseccomp-dev
        - git clone -b rt https://github.com/nasim-samimi/runc.git /tmp/runc-rt
        - cd /tmp/runc-rt && make
        - cd /tmp/runc-rt && sudo install -D -m0755 runc /usr/local/sbin/runc
        - sudo systemctl daemon-reload
        - sudo systemctl restart containerd
      files:
        - contentFrom:
            secret:
              key: worker-node-azure.json
              name: rt-capi-md-0-azure-json
          owner: root:root
          path: /etc/kubernetes/azure.json
          permissions: "0644"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            feature-gates: "DynamicResourceAllocation=true"
          name: '{{ ds.meta_data["local_hostname"] }}'
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: cluster-identity
  namespace: default
spec:
  type: ServicePrincipal
  tenantID: cb5b3c56-8331-4862-8e2c-369b8684fdc0
  clientID: 5796b248-d3e7-45de-b98c-880aa403b2cb
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  allowedNamespaces:
    list:
      - default
